
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class CC103Activity extends javax.swing.JFrame {

    /**
     * Creates new form CC103Activity
     */
    public CC103Activity() {
        initComponents();
        
        Icon i = turkey.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(turkey.getWidth(), turkey.getHeight(), Image.SCALE_SMOOTH);
        turkey.setIcon(new ImageIcon(image));
        
        Icon o = cheddar.getIcon();
        ImageIcon icon1 = (ImageIcon)o;
        Image image1 = icon1.getImage().getScaledInstance(cheddar.getWidth(), cheddar.getHeight(), Image.SCALE_SMOOTH);
        cheddar.setIcon(new ImageIcon(image1));
        
        Icon p = avocado.getIcon();
        ImageIcon icon2 = (ImageIcon)p;
        Image image2 = icon2.getImage().getScaledInstance(avocado.getWidth(), avocado.getHeight(), Image.SCALE_SMOOTH);
        avocado.setIcon(new ImageIcon(image2));
        
        Icon a = coffee2.getIcon();
        ImageIcon icon3 = (ImageIcon)a;
        Image image3 = icon3.getImage().getScaledInstance(coffee2.getWidth(), coffee2.getHeight(), Image.SCALE_SMOOTH);
        coffee2.setIcon(new ImageIcon(image3));
        
        Icon s = coffee1.getIcon();
        ImageIcon icon4 = (ImageIcon)s;
        Image image4 = icon4.getImage().getScaledInstance(coffee1.getWidth(), coffee1.getHeight(), Image.SCALE_SMOOTH);
        coffee1.setIcon(new ImageIcon(image4));
        
        Icon d = coffee3.getIcon();
        ImageIcon icon5 = (ImageIcon)d;
        Image image5 = icon5.getImage().getScaledInstance(coffee3.getWidth(), coffee3.getHeight(), Image.SCALE_SMOOTH);
        coffee3.setIcon(new ImageIcon(image5));
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oleatoRad = new javax.swing.JRadioButton();
        whiteRad = new javax.swing.JRadioButton();
        mochaRad = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        avocadoCheck = new javax.swing.JCheckBox();
        turkeyCheck = new javax.swing.JCheckBox();
        cheddarCheck = new javax.swing.JCheckBox();
        rad8 = new javax.swing.JRadioButton();
        rad12 = new javax.swing.JRadioButton();
        rad16 = new javax.swing.JRadioButton();
        rad20 = new javax.swing.JRadioButton();
        coldBtn = new javax.swing.JRadioButton();
        hotBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sub = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkoutBtn = new javax.swing.JToggleButton();
        clearBtn = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        subTotal = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        finalTotal = new javax.swing.JTextPane();
        clearBtn1 = new javax.swing.JToggleButton();
        clearBtn2 = new javax.swing.JToggleButton();
        turkey = new javax.swing.JLabel();
        cheddar = new javax.swing.JLabel();
        avocado = new javax.swing.JLabel();
        coffee1 = new javax.swing.JLabel();
        coffee2 = new javax.swing.JLabel();
        coffee3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 221, 154));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setForeground(new java.awt.Color(61, 170, 107));

        jLabel1.setFont(new java.awt.Font("Kunstler Script", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shappy");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Size");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Drinks");

        buttonGroup1.add(oleatoRad);
        oleatoRad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        oleatoRad.setText("Oleato - 180 PHP");
        oleatoRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oleatoRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(whiteRad);
        whiteRad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        whiteRad.setText("White Chocolate - 210 PHP");
        whiteRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteRadActionPerformed(evt);
            }
        });

        buttonGroup1.add(mochaRad);
        mochaRad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        mochaRad.setText("Mocha Cookie Crumble - 190 PHP");
        mochaRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaRadActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Sandwiches");

        avocadoCheck.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        avocadoCheck.setText("Avocado Spread - 159 PHP");
        avocadoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avocadoCheckActionPerformed(evt);
            }
        });

        turkeyCheck.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        turkeyCheck.setText("Turkey Bacon - 239 PHP");
        turkeyCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turkeyCheckActionPerformed(evt);
            }
        });

        cheddarCheck.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cheddarCheck.setText("Cheddar and Egg Sandwich - 169 PHP");
        cheddarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheddarCheckActionPerformed(evt);
            }
        });

        buttonGroup2.add(rad8);
        rad8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rad8.setText("8 oz + 19 PHP");
        rad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad8ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rad12);
        rad12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rad12.setText("12 oz + 29 PHP");
        rad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad12ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rad16);
        rad16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rad16.setText("16 oz + 39 PHP");
        rad16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad16ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rad20);
        rad20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rad20.setText("20 oz + 59 PHP");
        rad20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad20ActionPerformed(evt);
            }
        });

        buttonGroup3.add(coldBtn);
        coldBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        coldBtn.setText("Cold - 10 PHP");
        coldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldBtnActionPerformed(evt);
            }
        });

        buttonGroup3.add(hotBtn);
        hotBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        hotBtn.setText("Hot - 15 PHP");
        hotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Preference");

        sub.setEditable(false);
        sub.setText("0");
        jScrollPane2.setViewportView(sub);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Subtotal:");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Subtotal:");

        checkoutBtn.setText("Check Out");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        subTotal.setEditable(false);
        subTotal.setText("0");
        jScrollPane3.setViewportView(subTotal);

        jScrollPane1.setViewportView(finalTotal);

        clearBtn1.setText("Clear");
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });

        clearBtn2.setText("Clear");
        clearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn2ActionPerformed(evt);
            }
        });

        turkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Turkey.jpg"))); // NOI18N

        cheddar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vitor-monthay-8DcjZWBPHb4-unsplash.jpg"))); // NOI18N

        avocado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avocado.jpg"))); // NOI18N

        coffee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee1.jpg"))); // NOI18N
        coffee1.setText("coffee");

        coffee2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee2.jpg"))); // NOI18N

        coffee3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/whiteChoco.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rad16)
                                        .addComponent(rad12)
                                        .addComponent(rad20))
                                    .addComponent(jLabel5)
                                    .addComponent(rad8))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(coldBtn)
                                    .addComponent(hotBtn)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(avocado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(132, 132, 132)
                                            .addComponent(turkey, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cheddar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(coffee2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(avocadoCheck))
                                            .addGap(103, 103, 103)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(turkeyCheck)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(clearBtn1)
                                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(coffee1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(86, 86, 86)
                                            .addComponent(cheddarCheck))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(109, 109, 109)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(oleatoRad)
                                                .addComponent(coffee3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(mochaRad)
                                    .addGap(63, 63, 63)
                                    .addComponent(whiteRad)))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(checkoutBtn)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clearBtn2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(avocado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(turkey, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheddar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avocadoCheck)
                    .addComponent(turkeyCheck)
                    .addComponent(cheddarCheck))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(clearBtn1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coffee1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coffee2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mochaRad)
                    .addComponent(whiteRad)
                    .addComponent(oleatoRad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coldBtn)
                        .addGap(8, 8, 8)
                        .addComponent(hotBtn)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad12)
                        .addGap(8, 8, 8)
                        .addComponent(rad16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutBtn)
                    .addComponent(clearBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1908, 1908, 1908))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oleatoRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oleatoRadActionPerformed
        // Coffee Option
        int price = 0;
        sub.setText("0");
        
        if (oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }
        
    }//GEN-LAST:event_oleatoRadActionPerformed

    private void avocadoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avocadoCheckActionPerformed
        // TODO add your handling code here:
        int price = 0;
        
        subTotal.setText("0");
        if (avocadoCheck.isSelected()){
            price = price + 159;
            subTotal.setText(Integer.toString(price));
         }
        if (turkeyCheck.isSelected()){
            price = price + 239;
            subTotal.setText(Integer.toString(price));
         }
        if (cheddarCheck.isSelected()){
            price = price + 169;
            subTotal.setText(Integer.toString(price));
         }
        
       
    }//GEN-LAST:event_avocadoCheckActionPerformed

    private void turkeyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkeyCheckActionPerformed
        // Turkey
        int price = 0;
        subTotal.setText("0");
        
        if (avocadoCheck.isSelected()){
            price = price + 159;
            subTotal.setText(Integer.toString(price));
         }
        if (turkeyCheck.isSelected()){
            price = price + 239;
            subTotal.setText(Integer.toString(price));
         }
        if (cheddarCheck.isSelected()){
            price = price + 169;
            subTotal.setText(Integer.toString(price));
         }
        
        
    }//GEN-LAST:event_turkeyCheckActionPerformed

    private void cheddarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheddarCheckActionPerformed
        // Cheddar
        
        int price = 0;
        subTotal.setText("0");
        
        if (avocadoCheck.isSelected()){
            price = price + 159;
            subTotal.setText(Integer.toString(price));
         }
        if (turkeyCheck.isSelected()){
            price = price + 239;
            subTotal.setText(Integer.toString(price));
         }
        if (cheddarCheck.isSelected()){
            price = price + 169;
            subTotal.setText(Integer.toString(price));
         }
    }//GEN-LAST:event_cheddarCheckActionPerformed

    private void whiteRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteRadActionPerformed
        // White Chocolate Code
        int price = 0;
        sub.setText("0");
        
        if (whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }
        if (mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }
    }//GEN-LAST:event_whiteRadActionPerformed

    private void mochaRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaRadActionPerformed
        // Mocha Code
        
        int price = 0;
        sub.setText("0");
        
        if (mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }
    }//GEN-LAST:event_mochaRadActionPerformed

    private void rad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad8ActionPerformed
        // int price = 0;
        int price = 0;
        int additional;
        sub.setText("0");
        
        if (oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }
        if (rad8.isSelected()){
            additional = price + 19;
            sub.setText(Integer.toString(additional));    
        }else if(rad12.isSelected()){
            additional = price + 29;
            sub.setText(Integer.toString(additional));  
        }else if(rad16.isSelected()){
            additional = price + 39;
            sub.setText(Integer.toString(additional));  
        }else if(rad20.isSelected()){
            additional = price + 59;
            sub.setText(Integer.toString(additional));  
        }
    }//GEN-LAST:event_rad8ActionPerformed

    private void rad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad12ActionPerformed
        // TODO add your handling code here:
        int price = 0;
        int additional;
        sub.setText("0");
        
        if (oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }
        if (rad8.isSelected()){
            additional = price + 19;
            sub.setText(Integer.toString(additional));    
        }else if(rad12.isSelected()){
            additional = price + 29;
            sub.setText(Integer.toString(additional));  
        }else if(rad16.isSelected()){
            additional = price + 39;
            sub.setText(Integer.toString(additional));  
        }else if(rad20.isSelected()){
            additional = price + 59;
            sub.setText(Integer.toString(additional));  
        }
    }//GEN-LAST:event_rad12ActionPerformed

    private void rad16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad16ActionPerformed
        // TODO add your handling code here:
        int price = 0;
        int additional;
        sub.setText("0");
        
        if (oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }
        if (rad8.isSelected()){
            additional = price + 19;
            sub.setText(Integer.toString(additional));    
        }else if(rad12.isSelected()){
            additional = price + 29;
            sub.setText(Integer.toString(additional));  
        }else if(rad16.isSelected()){
            additional = price + 39;
            sub.setText(Integer.toString(additional));  
        }else if(rad20.isSelected()){
            additional = price + 59;
            sub.setText(Integer.toString(additional));  
        }
    }//GEN-LAST:event_rad16ActionPerformed

    private void rad20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad20ActionPerformed
        // TODO add your handling code here:
        int price = 0;
        int additional;
        sub.setText("0");
        
        if (oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }
        if (rad8.isSelected()){
            additional = price + 19;
            sub.setText(Integer.toString(additional));    
        }else if(rad12.isSelected()){
            additional = price + 29;
            sub.setText(Integer.toString(additional));  
        }else if(rad16.isSelected()){
            additional = price + 39;
            sub.setText(Integer.toString(additional));  
        }else if(rad20.isSelected()){
            additional = price + 59;
            sub.setText(Integer.toString(additional));  
        }
    }//GEN-LAST:event_rad20ActionPerformed

    private void coldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldBtnActionPerformed
        // TODO add your handling code here:
        int price = 0;
        int additional = 0;
        int pref;
        sub.setText("0");
        
        if (oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }if(rad8.isSelected()){
            additional = price + 19;
            sub.setText(Integer.toString(additional));    
        }else if(rad12.isSelected()){
            additional = price + 29;
            sub.setText(Integer.toString(additional));  
        }else if(rad16.isSelected()){
            additional = price + 39;
            sub.setText(Integer.toString(additional));  
        }else if(rad20.isSelected()){
            additional = price + 59;
            sub.setText(Integer.toString(additional));  
        }if (coldBtn.isSelected()){
            pref = additional + 10;
            sub.setText(Integer.toString(pref));
        }else if(hotBtn.isSelected()){
            pref = additional + 15;
            sub.setText(Integer.toString(pref));
        }
    }//GEN-LAST:event_coldBtnActionPerformed

    private void hotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotBtnActionPerformed
        // TODO add your handling code here:
        int price = 0;
        int additional = 0;
        int pref;
        sub.setText("0");
        if (oleatoRad.isSelected()){
            price = price + 180;
            sub.setText(Integer.toString(price));   
        }else if(whiteRad.isSelected()){
            price = price + 210;
            sub.setText(Integer.toString(price));   
        }else if(mochaRad.isSelected()){
            price = price + 190;
            sub.setText(Integer.toString(price));   
        }if(rad8.isSelected()){
            additional = price + 19;
            sub.setText(Integer.toString(additional));    
        }else if(rad12.isSelected()){
            additional = price + 29;
            sub.setText(Integer.toString(additional));  
        }else if(rad16.isSelected()){
            additional = price + 39;
            sub.setText(Integer.toString(additional));  
        }else if(rad20.isSelected()){
            additional = price + 59;
            sub.setText(Integer.toString(additional));  
        }if (coldBtn.isSelected()){
            pref = additional + 10;
            sub.setText(Integer.toString(pref));
        }else if(hotBtn.isSelected()){
            pref = additional + 15;
            sub.setText(Integer.toString(pref));
        }
        
    }//GEN-LAST:event_hotBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
        
        try {
    int sandwichCost = Integer.parseInt(subTotal.getText());
    int drinkCost = Integer.parseInt(sub.getText());

    // Reset text fields
    sub.setText("0");
    subTotal.setText("0");

    // Calculate the total cost
    int totalCost = sandwichCost + drinkCost;
    String message = "Your total purchase is " + totalCost;
    finalTotal.setText(message);

    // Clear radio buttons
    
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();

    // Clear checkboxes
    JCheckBox[] checkBoxes = {avocadoCheck, turkeyCheck, cheddarCheck};
    for (JCheckBox checkBox : checkBoxes) {
        checkBox.setSelected(false);
    }
} catch (NumberFormatException e) {
    // Handle invalid input
    finalTotal.setText("Error: Invalid input");
}
        
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        finalTotal.setText("");
        finalTotal.requestFocusInWindow();
        
        sub.setText("0");
        sub.requestFocusInWindow();
        
        subTotal.setText("0");
        subTotal.requestFocusInWindow();
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        
        avocadoCheck.setSelected(false);
        turkeyCheck.setSelected(false);
        cheddarCheck.setSelected(false);
            
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        // TODO add your handling code here:
        
        subTotal.setText("0");
        subTotal.requestFocusInWindow();
        
        avocadoCheck.setSelected(false);
        turkeyCheck.setSelected(false);
        cheddarCheck.setSelected(false);
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void clearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn2ActionPerformed
        sub.setText("0");
        sub.requestFocusInWindow();
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
    }//GEN-LAST:event_clearBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CC103Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CC103Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CC103Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CC103Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CC103Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avocado;
    private javax.swing.JCheckBox avocadoCheck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JToggleButton checkoutBtn;
    private javax.swing.JLabel cheddar;
    private javax.swing.JCheckBox cheddarCheck;
    private javax.swing.JToggleButton clearBtn;
    private javax.swing.JToggleButton clearBtn1;
    private javax.swing.JToggleButton clearBtn2;
    private javax.swing.JLabel coffee1;
    private javax.swing.JLabel coffee2;
    private javax.swing.JLabel coffee3;
    private javax.swing.JRadioButton coldBtn;
    private javax.swing.JTextPane finalTotal;
    private javax.swing.JRadioButton hotBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton mochaRad;
    private javax.swing.JRadioButton oleatoRad;
    private javax.swing.JRadioButton rad12;
    private javax.swing.JRadioButton rad16;
    private javax.swing.JRadioButton rad20;
    private javax.swing.JRadioButton rad8;
    private javax.swing.JTextPane sub;
    private javax.swing.JTextPane subTotal;
    private javax.swing.JLabel turkey;
    private javax.swing.JCheckBox turkeyCheck;
    private javax.swing.JRadioButton whiteRad;
    // End of variables declaration//GEN-END:variables
}
